<?php
require_once __DIR__ . '/modules/WooProductsFilters/WooProductsFilters.php';
require_once __DIR__ . '/modules/WooProductsFilters-child/WooProductsFilters-child.php';
require_once __DIR__ . '/modules/WooCartList/WooCartList.php';
require_once __DIR__ . '/modules/WooCartTotals/WooCartTotals.php';
require_once __DIR__ . '/modules/WooCheckoutBillingInfo/WooCheckoutBillingInfo.php';
require_once __DIR__ . '/modules/WooCheckoutCoupon/WooCheckoutCoupon.php';
require_once __DIR__ . '/modules/WooCheckoutOrderReview/WooCheckoutOrderReview.php';
require_once __DIR__ . '/modules/WooCheckoutShippingInfo/WooCheckoutShippingInfo.php';
require_once __DIR__ . '/modules/WooThankYou/WooThankYou.php';
require_once __DIR__ . '/modules/Abstracts/WooAccountBase.php';
require_once __DIR__ . '/modules/WooAccountUserImage/WooAccountUserImage.php';
require_once __DIR__ . '/modules/WooAccountUserName/WooAccountUserName.php';
require_once __DIR__ . '/modules/WooAccountNav/WooAccountNav.php';
require_once __DIR__ . '/modules/WooAccountNavItem/WooAccountNavItem.php';
// require_once __DIR__ . '/modules/WooAccountDashboard/WooAccountDashboard.php';
// require_once __DIR__ . '/modules/WooAccountOrders/WooAccountOrders.php';
// require_once __DIR__ . '/modules/WooAccountViewOrder/WooAccountViewOrder.php';
// require_once __DIR__ . '/modules/WooAccountDownloads/WooAccountDownloads.php';
// require_once __DIR__ . '/modules/WooAccountAddresses/WooAccountAddresses.php';
// require_once __DIR__ . '/modules/WooAccountDetails/WooAccountDetails.php';
require_once __DIR__ . '/modules/WooAccountContent/WooAccountContent.php';
require_once __DIR__ . '/modules/WooAccountContentItem/WooAccountContentItem.php';
require_once __DIR__ . '/modules/WooMiniCart/WooMiniCart.php';
require_once __DIR__ . '/modules/WooMultiStepCheckout/WooMultiStepCheckout.php';
require_once __DIR__ . '/modules/WooMultiStepCheckout-child/WooMultiStepCheckout-child.php';
require_once __DIR__ . '/modules/Abstracts/WooLoginRegisterForm.php';
require_once __DIR__ . '/modules/WooLoginForm/WooLoginForm.php';
require_once __DIR__ . '/modules/WooRegisterForm/WooRegisterForm.php';